[package]
name = "terranames"
version = "0.1.0"
authors = ["Jon Lund Steffensen <jonlst@gmail.com>"]
edition = "2018"

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "0.14.0"
cw20 = "0.6.1"
schemars = "0.8.3"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terra-cosmwasm = "2.0.0"
terraswap = "2.1.0"

[dev-dependencies]
cosmwasm-schema = "0.14.0"

[profile.dev]
overflow-checks = true

[profile.release]
overflow-checks = true
